version: '3.8'

services:
  jwt_util:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: jwt_utility
    environment:
      INPUT_DATA: 'input de prueba'
    secrets:
      - jwt_secret
secrets:
  jwt_secret:
    file: ./secret.txt

